### crawlingRequest
# @no-cookie-jar
GET http://localhost:8080/crawling/musinsa
Content-Type: application/json

### InsertBrandTest
POST http://localhost:8080/product/test
Content-Type: application/json

< ./brand.json